### ISSUE TITLE
Tracking issue: ESLint recommended rules

### ISSUE THREAD

**Issue by Stupremee** [rslint/rslint#105]
Tracking issue for rules from `eslint:recommended` set.

- [x] constructor-super
- [x] for-direction
- [x] getter-return
- [x] no-async
- [ ] no-case-declarations
- [ ] no-class-assign (blocked on scope analysis)
- [x] no-compare
- [x] no-cond
- [ ] no-const-assign (blocked on scope analysis)
- [x] no-constant
- [ ] no-control-regex
- [x] no-debugger
- [x] no-delete
- [ ] no-dupe-args
- [ ] no-dupe-class
- [ ] no-dupe-else
- [x] no-dupe
- [x] no-duplicate
- [x] no-empty
- [ ] no-empty-character
- [ ] no-empty-pattern
- [ ] no-ex-assign (blocked on scope analysis)
- [x] no-extra
- [x] no-extra
- [ ] no-fallthrough (blocked on flow analysis)
- [ ] no-func-assign (blocked on scope analysis)
- [ ] no-global-assign (blocked on scope analysis)
- [ ] no-import-assign (blocked on scope analysis)
- [x] no-inner
- [x] no-invalid
- [x] no-irregular
- [ ] no-misleading-character
- [ ] no-mixed-spaces
- [x] no-new
- [ ] no-obj-calls
- [ ] no-octal
- [x] no-prototype
- [ ] no-redeclare (blocked on scope analysis)
- [ ] no-regex-spaces
- [ ] no-self-assign
- [ ] no-setter-return
- [ ] no-shadow-restriced-names
- [x] no-sparse
- [x] no-this
- [ ] no-undef (blocked on scope analysis)
- [x] no-unexpected
- [ ] no-unreachable (blocked on scope analysis)
- [x] no-unsafe
- [x] no-unsafe
- [ ] no-unused-labels
- [ ] no-unused-vars (blocked on scope analysis)
- [x] no-useless
- [ ] no-with
- [ ] require-yield
- [x] use-isnan
- [x] valid-typeof

**Comment by Stupremee** [comment]
Yes, we are open to contributions! 
It's fine if you just link this tracking issue. 
For example contributions of new rules, you can look at some older PRs that add new rules, like #89.
