### ISSUE TITLE
Vendor regex_syntax into rslint_regex and change it to be ES2021 compliant

### ISSUE THREAD

**Issue by RDambrosio016** [rslint/rslint#69]
Following a discussion on discord, @bartlomieju, @magurotuna, and i have chosen to work on vendoring [regex_syntax](https://docs.rs/regex-syntax/0.6.20/regex_syntax/) as a new crate in rslint, rslint_regex. regex_syntax is not compliant to ES2021 therefore some work on the parser needs to be done, furthermore, we don't need the HIR produced in the crate, so that can be tossed as well. We should also replace the `Error` enum with `rslint_errors` diagnostics to provide more context and make it easier to work with. 

# TODO

- [x] Vendor regex_syntax
- [x] Remove HIR
- [ ] Replace Error with rslint_errors diagnostics
- [ ] Make the parser ES2021 compliant

**Comment by Stupremee** [comment]
Why do you want to vendor regex_syntax instead of writing a regex parser from scratch that is designed to work with the ECMA specification?
